export { LoginPage } from './LoginPage';
export { DashboardPage } from './DashboardPage';
export { SociPage } from './SociPage';
export { SocioNewPage } from './SocioNewPage';
export { SocioEditPage } from './SocioEditPage';
export { SocioDetailPage } from './SocioDetailPage';
export { StatusAssociativiPage } from './StatusAssociativiPage';
export { ScadenziarioPage } from './ScadenziarioPage';
export { StatiPagamentoPage } from './StatiPagamentoPage';
